### ISSUE TITLE
Kernel Fusion

### ISSUE THREAD

**Issue by andresnowak** [TilliFe/MojoGrad#11]
I saw that you have changed how the forward operations work, now you execute the forward operation the moment it is added to the graph, but wouldn't it be better to do it the way it was before to be able to add the ability of kernel fusion and reducing the amount of memory used (reducing the amount of output memory tensors that are created), so basically to have lazy tensors.

**Comment by TilliFe** [comment]
Hi, I agree and I should say that I am still elaborating on the actual architecture of the graph. This is definitely not done yet :)
I will discuss my thoughts next time.
