### ISSUE TITLE
Please format with 'mojo format .'

### ISSUE THREAD

**Issue by HJLebbink** [TilliFe/MojoGrad#18]
I need to rebase once in a while, and most conflicts are due to unconventional layout mismatches.  

Could you please format the code with 'mojo format .'. I also don't always agree with its decisions, but at least its conventional...

Regards.

**Comment by TilliFe** [comment]
Thanks a lot. Please share ideas for architectural enhancements. I am still very much iterating through different ideas on the general architecture of the engine and I'd be really grateful for some valuable input or comments. :)
