### ISSUE TITLE
snake_case instead of camelCase

### ISSUE THREAD

**Issue by gryznar** [TilliFe/MojoGrad#2]
In Python, the leading convention is to use PascalCase for class names, UPPER_SNAKE_CASE for constants and snake_case for everything else. Mojo as Python superset is following this rule and do not use camelCase at all. I suggest to make this consistent and adjust code :)

**Comment by TilliFe** [comment]
Thank you. I changed it all. :)

**Comment by gryznar** [comment]
The same applies to filenames ;) file_name.mojo
