### ISSUE TITLE
Gradient/backward operators for Mean, Variance and Std

### ISSUE THREAD

**Issue by TilliFe** [TilliFe/MojoGrad#9]
The forward opators for mean, var and std have been implented, the backward operators in the forward.mojo and backward.mojo file are still marked with 'pass'. This needs to be implemented soon! :)

**Comment by ManishAradwad** [comment]
hi @TilliFe I'm currently working on implementing mean_grad, I didn't really get how mean function works. can you help me with it a little.

for ex. here it just seems to be adding a and b tensors irrespective of dims

<img width="470" alt="Screenshot 2023-10-25 at 8 08 47 PM" src="https://github.com/TilliFe/Infermo/assets/29497701/220ae9bf-1ab1-4161-9eb2-d0cceecfdd0c">


I'm guessing it has something to do with `other_params` of a tensor but can't figure out how
